# Generated by Django 3.0.2 on 2020-01-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200122_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_by_date',
        ),
    ]
